name: Build and lint Gradle project
on:
  push:
    branches: ["main"]

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v4
      - name: Upload Repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Editorconfig-checker:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  Markdown-cli:
    runs-on: ubuntu-latest
    needs: [Clone-down]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Setup markdown-cli tool
        run: npm install -g markdown-cli
      - name: Run markdown-cli tool
        run: markdown-cli **/*.md

  Test:
    runs-on: ubuntu-latest
    needs: [Editorconfig-checker, Markdown-cli]
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Test with Gradle
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

  Build:
    runs-on: ubuntu-latest
    needs: [Editorconfig-checker, Markdown-cli]
    container: gradle:6-jdk11
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Build with Gradle
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  # Linter:
  #   runs-on: ubuntu-latest
  #   needs: [Editorconfig-checker, Markdown-cli]
    
  # Docker-image:
  #   runs-on: ubuntu-latest
  #   needs: [Build,Test]
  #   steps:
  #   - name: Download code
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: code
  #       path: .
  #   - name: build docker
  #     run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
  #   - name: push docker
  #     run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
