name: Build and lint Gradle project
on:
  push:
    branches: ["main"]

jobs:
  Editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  Markdown-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Lint .md files
        run: npx --yes markdownlint-cli@latest "**/*.md" --ignore "node_modules" --ignore "dist"

  Build:
    runs-on: ubuntu-latest
    container: gradle:9-jdk24
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  Sonarqube:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disabling shallow clones is recommended for improving the relevancy of reporting
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-9-jdk24@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}

  Test:
    runs-on: ubuntu-latest
    needs: [Editorconfig-checker, Markdown-linter]
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v4
      - name: Test with Gradle
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

  # Linter:
  #   runs-on: ubuntu-latest
  #   needs: [Editorconfig-checker, Markdown-linter]

  # Docker-image:
  #   runs-on: ubuntu-latest
  #   needs: [Build,Test]
  #   steps:
  #   - name: Download code
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: code
  #       path: .
  #   - name: build docker
  #     run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
  #   - name: push docker
  #     run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
